#!/usr/bin/env bash
# Apply Mixel-Remote branding to an upstream RustDesk source checkout.
#
# Expected env: working directory contains a `rustdesk/` subdir with the
# upstream source already checked out. Branding configs and icons live in
# the parent (this repo) under branding/.
#
# Usage:
#   $RDREPO   = path to upstream rustdesk checkout (default: ./rustdesk)
#   $BRANDING = path to branding dir (default: ./branding)

set -euo pipefail

RDREPO="${RDREPO:-./rustdesk}"
BRANDING="${BRANDING:-./branding}"

if [[ ! -d "$RDREPO" ]]; then
  echo "❌ RustDesk source not found at $RDREPO"
  exit 1
fi

# shellcheck source=/dev/null
source "$BRANDING/branding.env"

echo "→ Applying branding: $APP_NAME ($MACOS_BUNDLE_ID) on top of RustDesk $UPSTREAM_VERSION"

# 1. Copy custom.txt — RustDesk's build-time override file.
cp "$BRANDING/custom.txt" "$RDREPO/custom.txt"

# 2. Replace the main app icon set. RustDesk holds icons at multiple
#    locations; we overwrite each so every platform builder picks ours up.
copy_icon () {
  local size="$1"
  local target="$2"
  if [[ -f "$BRANDING/icon-${size}.png" ]]; then
    cp "$BRANDING/icon-${size}.png" "$target"
    echo "   icon $size → $(basename "$target")"
  fi
}

# Linux/AppImage assets
copy_icon 16   "$RDREPO/res/icon.png" || true
copy_icon 256  "$RDREPO/res/256x256.png" || true
copy_icon 128  "$RDREPO/res/128x128@2x.png" || true
copy_icon 512  "$RDREPO/res/mac-tray-light.png" || true
copy_icon 512  "$RDREPO/res/mac-tray-dark.png" || true

# Flutter app assets
copy_icon 1024 "$RDREPO/flutter/assets/logo.png" || true
copy_icon 512  "$RDREPO/flutter/assets/icon.png" || true

# macOS .icns is generated from PNGs at build time by Flutter; placing
# multi-size PNGs in macos/Runner/Assets.xcassets/AppIcon.appiconset/
# is what actually rebrands the macOS app icon.
MAC_ICONSET="$RDREPO/flutter/macos/Runner/Assets.xcassets/AppIcon.appiconset"
if [[ -d "$MAC_ICONSET" ]]; then
  copy_icon 16   "$MAC_ICONSET/app_icon_16.png"
  copy_icon 32   "$MAC_ICONSET/app_icon_32.png"
  copy_icon 64   "$MAC_ICONSET/app_icon_64.png"
  copy_icon 128  "$MAC_ICONSET/app_icon_128.png"
  copy_icon 256  "$MAC_ICONSET/app_icon_256.png"
  copy_icon 512  "$MAC_ICONSET/app_icon_512.png"
  copy_icon 1024 "$MAC_ICONSET/app_icon_1024.png"
fi

# Windows .ico is generated from icon-*.png at build time by flutter_launcher_icons
WIN_ICON="$RDREPO/flutter/windows/runner/resources/app_icon.ico"
if [[ -f "$WIN_ICON" ]]; then
  magick \
    "$BRANDING/icon-16.png" \
    "$BRANDING/icon-32.png" \
    "$BRANDING/icon-48.png" \
    "$BRANDING/icon-64.png" \
    "$BRANDING/icon-128.png" \
    "$BRANDING/icon-256.png" \
    "$WIN_ICON"
  echo "   icon → app_icon.ico (multi-size)"
fi

# 3. Patch user-visible strings that custom.txt doesn't override.
#    We use sed on a known set of files. If upstream renames things, this
#    needs revisiting; that's why we pin UPSTREAM_VERSION above.
patch_string () {
  local file="$1" old="$2" new="$3"
  [[ -f "$RDREPO/$file" ]] || return 0
  if grep -q "$old" "$RDREPO/$file"; then
    sed -i.bak "s|$old|$new|g" "$RDREPO/$file" && rm -f "$RDREPO/$file.bak"
    echo "   patched: $file"
  fi
}

# macOS: bundle identifier and product name in xcconfig
patch_string flutter/macos/Runner/Configs/AppInfo.xcconfig \
  "PRODUCT_BUNDLE_IDENTIFIER = com.carriez.flutter_hbb" \
  "PRODUCT_BUNDLE_IDENTIFIER = $MACOS_BUNDLE_ID"
patch_string flutter/macos/Runner/Configs/AppInfo.xcconfig \
  "PRODUCT_NAME = RustDesk" \
  "PRODUCT_NAME = $APP_NAME"

# Linux .desktop file generated by flutter_distributor; rename product name
patch_string flutter/linux/CMakeLists.txt \
  'set(BINARY_NAME "rustdesk")' \
  "set(BINARY_NAME \"$APP_NAME_KEBAB\")"

# Windows runner: window title
patch_string flutter/windows/runner/main.cpp \
  '"rustdesk"' "\"$APP_NAME_KEBAB\""

# 4. Pre-bake server config — RustDesk reads RENDEZVOUS_SERVER from custom.txt
#    at build time, but we also stuff it into the runtime config in case the
#    user wipes their data dir.
mkdir -p "$RDREPO/.cargo"
cat > "$RDREPO/.cargo/config.toml" <<EOF
[env]
RENDEZVOUS_SERVER = "$RENDEZVOUS_SERVER"
RELAY_SERVER = "$RELAY_SERVER"
RS_PUB_KEY = "$RS_PUB_KEY"
EOF

echo "✓ Branding applied. Build with the standard RustDesk build instructions."
