#!/usr/bin/env python3
"""Serialize the pinned 1.4.6 keep-awake manager without changing its callers."""
from __future__ import annotations

import hashlib
import os
from pathlib import Path

SOURCE = "flutter/lib/common.dart"
START = "class WakelockManager {"
END = "\n/// call this to reload current window."
ORIGINAL_SHA256 = "d1136f48abedbeef843a3099dee3edcf6ae67c41654736fde2f1829df049dad9"

MANAGER = """class WakelockManager {
  // Mixel: serialize keep-awake requests and retain only successful state.
  static final Set<UniqueKey> _enabledKeys = {};
  static bool _mobileRequested = false;
  static bool _enabled = false;
  static bool _queued = false;
  static Future<void> _pending = Future<void>.value();

  static void enable(UniqueKey key, {bool isServer = false}) {
    // Preserve the outgoing-session preference and the server override.
    if (!isServer &&
        !mainGetLocalBoolOptionSync(kOptionKeepAwakeDuringOutgoingSessions)) {
      return;
    }
    if (isDesktop) {
      _enabledKeys.add(key);
    } else {
      _mobileRequested = true;
    }
    _schedule();
  }

  static void disable(UniqueKey key) {
    if (isDesktop) {
      _enabledKeys.remove(key);
    } else {
      _mobileRequested = false;
    }
    _schedule();
  }

  static void _schedule() {
    // Keep at most one follow-up callback behind an outstanding platform call.
    // Focus events must not grow a future chain while a provider is stalled.
    if (_queued) return;
    _queued = true;
    _pending = _pending.then((_) async {
      _queued = false;
      final requested = isDesktop ? _enabledKeys.isNotEmpty : _mobileRequested;
      if (requested == _enabled) return;
      try {
        // In particular, a Linux Inhibit must finish assigning its cookie
        // before a later UnInhibit can release it. Do not query enabled:
        // that platform method can fail on Android.
        if (requested) {
          await WakelockPlus.enable();
        } else {
          await WakelockPlus.disable();
        }
        _enabled = requested;
      } catch (_) {
        // Screensaver/power providers are optional. Keep the last successful
        // state so a later focus/session request can retry, without letting
        // a failed platform future escape into the remote-session UI.
        debugPrint('Keep-awake request could not be applied.');
      }
    });
  }
}
"""


def manager_range(text: str) -> tuple[int, int]:
    if text.count(START) != 1 or text.count(END) != 1:
        raise RuntimeError("Pinned keep-awake manager boundary missing or duplicated")
    start = text.index(START)
    end = text.index(END)
    if end <= start:
        raise RuntimeError("Pinned keep-awake manager boundary order changed")
    return start, end


def extract_manager(text: str) -> str:
    start, end = manager_range(text)
    return text[start:end].strip() + "\n"


def patch_common(text: str) -> str:
    start, end = manager_range(text)
    current = extract_manager(text)
    if current == MANAGER:
        return text
    if hashlib.sha256(current.encode("utf-8")).hexdigest() != ORIGINAL_SHA256:
        raise RuntimeError("Pinned keep-awake manager changed; refusing an unverified patch")
    # Preserve both neighboring source regions; only the verified class changes.
    return text[:start] + MANAGER + "\n" + text[end:]


def apply(repo: Path) -> None:
    source = repo / SOURCE
    original = source.read_text(encoding="utf-8")
    patched = patch_common(original)
    # Keep the generated bytes identical on Git Bash/Windows and Unix. Reading
    # text normalizes CRLF, so an already-patched CRLF checkout also needs this
    # one-time canonical write before subsequent applications can be no-ops.
    if source.read_bytes() != patched.encode("utf-8"):
        with source.open("w", encoding="utf-8", newline="\n") as output:
            output.write(patched)
    print("   installed verified serialized keep-awake manager")


if __name__ == "__main__":
    apply(Path(os.environ.get("RDREPO", "./rustdesk")).resolve())
